exports.SHERLOCK_CORE = [
  "conceptualise a ~ sherlock thing ~ S that is an entity and is an imageable thing",
  "conceptualise an ~ organisation ~ O that is a sherlock thing",
  "conceptualise a ~ fruit ~ F that is a sherlock thing and is a locatable thing",
  "conceptualise a ~ room ~ R that is a location and is a sherlock thing",
  "conceptualise a ~ shirt colour ~ C",
  "conceptualise a ~ sport ~ S",
  "conceptualise a ~ character ~ C that is a sherlock thing and is a locatable thing and has the shirt colour C as ~ shirt colour ~",
  "conceptualise the character C ~ works for ~ the organisation O and ~ eats ~ the fruit F and ~ plays ~ the sport S",
  "conceptualise the shirt colour C ~ is worn by ~ the character C",
  "conceptualise the room R ~ contains ~ the fruit F and has the character C as ~ contents ~",
  "conceptualise the fruit F ~ is eaten by ~ the character C",
  "conceptualise the sport S ~ is played by ~ the character C",
  "conceptualise a ~ question ~ Q that has the value V as ~ text ~ and has the value W as ~ value ~ and has the value X as ~ relationship ~",
  "conceptualise the question Q ~ concerns ~ the sherlock thing C",

  "there is a rule named r1 that has 'if the character C ~ eats ~ the fruit F then the fruit F ~ is eaten by ~ the character C' as instruction",
  "there is a rule named r2 that has 'if the character C ~ plays ~ the sport S then the sport S ~ is played by ~ the character C' as instruction",
  "there is a rule named r3 that has 'if the character C has the shirt colour S as ~ shirt colour ~ then the shirt colour S ~ is worn by ~ the character C' as instruction",
  "there is a rule named r4 that has 'if the character C ~ is in ~ the room R then the room R has the character C as ~ contents ~' as instruction",
  "there is a rule named r5 that has 'if the fruit F ~ is in ~ the room R then the room R ~ contains ~ the fruit F' as instruction",
  
  // Inverse rules:
  "there is a rule named r6 that has 'if the fruit F ~ is eaten by ~ the character C then the character C ~ eats ~ the fruit F' as instruction",
  "there is a rule named r7 that has 'if the sport S ~ is played by ~ the character C then the character C ~ plays ~ the sport S' as instruction",
  "there is a rule named r8 that has 'if the shirt colour S ~ is worn by ~ the character C then the character C has the shirt colour S as ~ shirt colour ~' as instruction",
  "there is a rule named r9 that has 'if the room R has the character C as ~ contents ~ then the character C ~ is in ~ the room R' as instruction",
  "there is a rule named r10 that has 'if the room R ~ contains ~ the fruit F then the fruit F ~ is in ~ the room R' as instruction",

  "there is an organisation named 'police'",
  "there is a character named 'Prof Crane' that has 'http://sherlock.cenode.io/media/crane.png' as image",
  "there is a character named 'Dr Finch' that has 'http://sherlock.cenode.io/media/finch.png' as image",
  "there is a character named 'Col Robin' that has 'http://sherlock.cenode.io/media/robin.png' as image",
  "there is a character named 'Sgt Stork' that has 'http://sherlock.cenode.io/media/stork.png' as image",
  "there is a character named 'Rev Hawk' that has 'http://sherlock.cenode.io/media/hawk.png' as image",
  "there is a character named 'Capt Falcon' that has 'http://sherlock.cenode.io/media/falcon.png' as image",
  "there is a room named 'Ruby Room'",
  "there is a room named 'Sapphire Room'",
  "there is a room named 'Gold Room'",
  "there is a room named 'Amber Room'",
  "there is a room named 'Emerald Room'",
  "there is a room named 'Silver Room'",
  "there is a fruit named 'pineapple'",
  "there is a fruit named 'apple'",
  "there is a fruit named 'banana'",
  "there is a fruit named 'orange'",
  "there is a fruit named 'lemon'",
  "there is a fruit named 'pear'",
  "there is a fruit named 'grape'",
  "there is a fruit named 'kiwi'",
  "there is a fruit named 'tomato'",
  "there is a shirt colour named 'green'",
  "there is a shirt colour named 'red'",
  "there is a shirt colour named 'yellow'",
  "there is a shirt colour named 'black'",
  "there is a shirt colour named 'white'",
  "there is a shirt colour named 'purple'",
  "there is a shirt colour named 'pink'",
  "there is a shirt colour named 'blue'",
  "there is a shirt colour named 'brown'",
  "there is a shirt colour named 'grey'",
  "there is a sport named 'tennis'",
  "there is a sport named 'badminton'",
  "there is a sport named 'rugby'",
  "there is a sport named 'football'",
  "there is a sport named 'soccer'",
  "there is a sport named 'running'",
  "there is a sport named 'swimming'",
  "there is a sport named 'athletic'",
  "there is a sport named 'baseball'",
  "there is a sport named 'rounders'",
  "there is a sport named 'softball'",
  "there is a sport named 'cricket'",
  "there is a sport named 'golf'",

  "there is a question named 'q1' that has 'What character eats pineapples?' as text and has 'is eaten by' as relationship and concerns the sherlock thing 'pineapple'",
  "there is a question named 'q2' that has 'What sport does Dr Finch play?' as text and has 'plays' as relationship and concerns the sherlock thing 'Dr Finch'",
  "there is a question named 'q3' that has 'What character eats apples?' as text and has 'is eaten by' as relationship and concerns the sherlock thing 'apple'",
  "there is a question named 'q4' that has 'What colour shirt is Prof Crane wearing?' as text and has 'shirt colour' as value and concerns the sherlock thing 'Prof Crane'",
  "there is a question named 'q6' that has 'Where is Col Robin?' as text and has 'is in' as relationship and concerns the sherlock thing 'Col Robin'",
  "there is a question named 'q7' that has 'What colour shirt is Sgt Stork wearing?' as text and has 'shirt colour' as value and concerns the sherlock thing 'Sgt Stork'",
  "there is a question named 'q8' that has 'Where is Sgt Stork?' as text and has 'is in' as relationship and concerns the sherlock thing 'Sgt Stork'",
  "there is a question named 'q9' that has 'Which character is in the emerald room?' as text and has 'contents' as value and concerns the sherlock thing 'Emerald Room'",
  "there is a question named 'q12' that has 'What character eats bananas?' as text and has 'is eaten by' as relationship and concerns the sherlock thing 'banana'",
  "there is a question named 'q13' that has 'What character is in the sapphire room?' as text and has 'contents' as value and concerns the sherlock thing 'Sapphire Room'",
  "there is a question named 'q17' that has 'What sport does Prof Crane play?' as text and has 'plays' as relationship and concerns the sherlock thing 'Prof Crane'",
  "there is a question named 'q18' that has 'What character is wearing a red shirt?' as text and has 'is worn by' as relationship and concerns the sherlock thing 'red'",
  "there is a question named 'q19' that has 'What character plays rugby?' as text and has 'is played by' as relationship and concerns the sherlock thing 'rugby'",
  "there is a question named 'q20' that has 'What fruit does Rev Hawk eat?' as text and has 'eats' as relationship and concerns the sherlock thing 'Rev Hawk'",
  "there is a question named 'q23' that has 'What fruit does Col Robin eat?' as text and has 'eats' as relationship and concerns the sherlock thing 'Col Robin'",
  "there is a question named 'q24' that has 'What colour shirt is Dr Finch wearing?' as text and has 'shirt colour' as value and concerns the sherlock thing 'Dr Finch'",
  "there is a question named 'q25' that has 'Where is the apple?' as text and has 'is in' as relationship and concerns the sherlock thing 'apple'",
  "there is a question named 'q26' that has 'What character is wearing a yellow shirt?' as text and has 'is worn by' as relationship and concerns the sherlock thing 'yellow'",
  "there is a question named 'q28' that has 'What fruit is in the silver room?' as text and has 'contains' as relationship and concerns the sherlock thing 'Silver Room'",
  "there is a question named 'q30' that has 'What character is wearing a black shirt?' as text and has 'is worn by' as relationship and concerns the sherlock thing 'black'",
  "there is a question named 'q31' that has 'What character eats lemons?' as text and has 'is eaten by' as relationship and concerns the sherlock thing 'lemon'",
  "there is a question named 'q33' that has 'What fruit does Prof Crane eat?' as text and has 'eats' as relationship and concerns the sherlock thing 'Prof Crane'",
  "there is a question named 'q34' that has 'What character plays baseball?' as text and has 'is played by' as relationship and concerns the sherlock thing 'baseball'",
  "there is a question named 'q35' that has 'What character plays soccer?' as text and has 'is played by' as relationship and concerns the sherlock thing 'soccer'",
  "there is a question named 'q36' that has 'What sport does Sgt Stork play?' as text and has 'plays' as relationship and concerns the sherlock thing 'Sgt Stork'",
  "there is a question named 'q37' that has 'What character is in the ruby room?' as text and has 'contents' as value and concerns the sherlock thing 'Ruby Room'",
  "there is a question named 'q39' that has 'What character plays golf?' as text and has 'is played by' as relationship and concerns the sherlock thing 'golf'",
  "there is a question named 'q40' that has 'What character eats oranges?' as text and has 'is eaten by' as relationship and concerns the sherlock thing 'orange'",
  "there is a question named 'q41' that has 'What colour shirt is Capt Falcon wearing?' as text and has 'shirt colour' as value and concerns the sherlock thing 'Capt Falcon'",
  "there is a question named 'q45' that has 'What character is in the amber room?' as text and has 'contents' as value and concerns the sherlock thing 'Amber Room'",
  "there is a question named 'q47' that has 'Where is Prof Crane?' as text and has 'is in' as relationship and concerns the sherlock thing 'Prof Crane'",
  "there is a question named 'q48' that has 'Where is the pear?' as text and has 'is in' as relationship and concerns the sherlock thing 'pear'",
  "there is a question named 'q50' that has 'What fruit does Sgt Stork eat?' as text and has 'eats' as relationship and concerns the sherlock thing 'Sgt Stork'",
  "there is a question named 'q52' that has 'What sport does Col Robin play?' as text and has 'plays' as relationship and concerns the sherlock thing 'Col Robin'",
  "there is a question named 'q53' that has 'Where is Capt Falcon?' as text and has 'is in' as relationship and concerns the sherlock thing 'Capt Falcon'",
  "there is a question named 'q54' that has 'What sport does Capt Falcon play?' as text and has 'plays' as relationship and concerns the sherlock thing 'Capt Falcon'"
];

exports.SHERLOCK_CW = [
  "conceptualise a ~ sherlock thing ~ S that is an entity and is an imageable thing",
  "conceptualise an ~ organisation ~ O that is a sherlock thing",
  "conceptualise a ~ fruit ~ F that is a sherlock thing and is a locatable thing",
  "conceptualise a ~ room ~ R that is a location and is a sherlock thing",
  "conceptualise a ~ coloured hat ~ C",
  "conceptualise a ~ sport ~ S",
  "conceptualise a ~ character ~ C that is a sherlock thing and is a locatable thing and has the coloured hat C as ~ coloured hat ~",
  "conceptualise the character C ~ works for ~ the organisation O and ~ eats ~ the fruit F and ~ plays ~ the sport S",
  "conceptualise the coloured hat C ~ is worn by ~ the character C",
  "conceptualise the room R ~ contains ~ the fruit F and has the character C as ~ contents ~",
  "conceptualise the fruit F ~ is eaten by ~ the character C",
  "conceptualise the sport S ~ is played by ~ the character C",
  "conceptualise a ~ question ~ Q that has the value V as ~ text ~ and has the value W as ~ value ~ and has the value X as ~ relationship ~",
  "conceptualise the question Q ~ concerns ~ the sherlock thing C",

  "there is a rule named r1 that has 'if the character C ~ eats ~ the fruit F then the fruit F ~ is eaten by ~ the character C' as instruction",
  "there is a rule named r2 that has 'if the character C ~ plays ~ the sport S then the sport S ~ is played by ~ the character C' as instruction",
  "there is a rule named r3 that has 'if the character C has the coloured hat S as ~ coloured hat ~ then the coloured hat S ~ is worn by ~ the character C' as instruction",
  "there is a rule named r4 that has 'if the character C ~ is in ~ the room R then the room R has the character C as ~ contents ~' as instruction",
  "there is a rule named r5 that has 'if the fruit F ~ is in ~ the room R then the room R ~ contains ~ the fruit F' as instruction",
  
  // Inverse rules:
  "there is a rule named r6 that has 'if the fruit F ~ is eaten by ~ the character C then the character C ~ eats ~ the fruit F' as instruction",
  "there is a rule named r7 that has 'if the sport S ~ is played by ~ the character C then the character C ~ plays ~ the sport S' as instruction",
  "there is a rule named r8 that has 'if the coloured hat S ~ is worn by ~ the character C then the character C has the coloured hat S as ~ coloured hat ~' as instruction",
  "there is a rule named r9 that has 'if the room R has the character C as ~ contents ~ then the character C ~ is in ~ the room R' as instruction",
  "there is a rule named r10 that has 'if the room R ~ contains ~ the fruit F then the fruit F ~ is in ~ the room R' as instruction",

  "there is an organisation named 'police'",
  "there is a character named 'Eliffant' that has 'http://sherlock.cenode.io/media/crane.png' as image",
  "there is a character named 'Jiraff' that has 'http://sherlock.cenode.io/media/finch.png' as image",
  "there is a character named 'Hipopotamws' that has 'http://sherlock.cenode.io/media/robin.png' as image",
  "there is a character named 'Llewpard' that has 'http://sherlock.cenode.io/media/stork.png' as image",
  "there is a character named 'Llew' that has 'http://sherlock.cenode.io/media/hawk.png' as image",
  "there is a character named 'Sebra' that has 'http://sherlock.cenode.io/media/falcon.png' as image",
  "there is a room named 'Ystafell Casnewydd'",
  "there is a room named 'Ystafell Caerdydd'",
  "there is a room named 'Ystafell Blaenafon'",
  "there is a room named 'Ystafell Caernarfon'",
  "there is a room named 'Ystafell Abertawe'",
  "there is a room named 'Ystafell Aberystwyth'",
  "there is a fruit named 'pinafal'",
  "there is a fruit named 'afal'",
  "there is a fruit named 'banana'",
  "there is a fruit named 'oren'",
  "there is a fruit named 'lemwn'",
  "there is a fruit named 'gellygen'",
  "there is a fruit named 'grape'",
  "there is a fruit named 'kiwi'",
  "there is a fruit named 'tomato'",
  "there is a coloured hat named 'gwyrdd'",
  "there is a coloured hat named 'coch'",
  "there is a coloured hat named 'glas'",
  "there is a coloured hat named 'pinc'",
  "there is a coloured hat named 'melyn'",
  "there is a coloured hat named 'oren'",
  "there is a coloured hat named 'pink'",
  "there is a coloured hat named 'blue'",
  "there is a coloured hat named 'brown'",
  "there is a coloured hat named 'grey'",
  "there is a sport named 'tenis'",
  "there is a sport named 'rygbi'",
  "there is a sport named 'pel droed'",
  "there is a sport named 'golff'",
  "there is a sport named 'pel fasged'",
  "there is a sport named 'criced'",
  "there is a sport named 'swimming'",
  "there is a sport named 'athletic'",
  "there is a sport named 'baseball'",
  "there is a sport named 'rounders'",
  "there is a sport named 'softball'",
  "there is a sport named 'cricket'",
  "there is a sport named 'golf'",

 
  "there is a question named 'q1' that has 'is eaten by' as relationship and concerns the sherlock thing 'pinafal'",
  "there is a question named 'q2' that has 'coloured hat' as value and concerns the sherlock thing 'hipopotamws'",
  "there is a question named 'q3' that has 'eats' as relationship and concerns the sherlock thing 'llew'",
  "there is a question named 'q4' that has 'is in' as relationship and concerns the sherlock thing 'afal'",
  "there is a question named 'q5' that has 'contents' as value and concerns the sherlock thing 'ystafell blaenafon'",
  "there is a question named 'q6' that has 'plays' as relationship and concerns the sherlock thing 'sebra'",
  "there is a question named 'q7' that has 'is in' as relationship and concerns the sherlock thing 'llewpard'",
  "there is a question named 'q8' that has 'coloured hat' as value and concerns the sherlock thing 'jiraff'",
  "there is a question named 'q9' that has 'is in' as relationship and concerns the sherlock thing 'lemwn'",
  "there is a question named 'q10' that has 'is played by' as relationship and concerns the sherlock thing 'rygbi'",
  "there is a question named 'q11' that has 'contents' as value and concerns the sherlock thing 'ystafell caerdydd'",
  "there is a question named 'q12' that has 'is in' as relationship and concerns the sherlock thing 'oren'",
  "there is a question named 'q13' that has 'is worn by' as relationship and concerns the sherlock thing 'pinc'",
  "there is a question named 'q14' that has 'is in' as relationship and concerns the sherlock thing 'eliffant'",
  "there is a question named 'q15' that has 'eats' as relationship and concerns the sherlock thing 'sebra'",
  "there is a question named 'q16' that has 'contents' as value and concerns the sherlock thing 'ystafell abertawe'",
  "there is a question named 'q17' that has 'coloured hat' as value and concerns the sherlock thing 'llewpard'",
  "there is a question named 'q18' that has 'plays' as relationship and concerns the sherlock thing 'eliffant'",
  "there is a question named 'q19' that has 'is eaten by' as relationship and concerns the sherlock thing 'banana'",
  "there is a question named 'q20' that has 'is in' as relationship and concerns the sherlock thing 'gellygen'",
  "there is a question named 'q21' that has 'coloured hat' as value and concerns the sherlock thing 'eliffant'",
  "there is a question named 'q22' that has 'plays' as relationship and concerns the sherlock thing 'hipopotamws'",
  "there is a question named 'q23' that has 'is in' as relationship and concerns the sherlock thing 'llew'",
  "there is a question named 'q24' that has 'coloured hat' as value and concerns the sherlock thing 'sebra'",
  "there is a question named 'q25' that has 'plays' as relationship and concerns the sherlock thing 'llewpard'",
  "there is a question named 'q26' that has 'is in' as relationship and concerns the sherlock thing 'sebra'",
  "there is a question named 'q27' that has 'is eaten by' as relationship and concerns the sherlock thing 'gellygen'",
  "there is a question named 'q28' that has 'plays' as relationship and concerns the sherlock thing 'llew'",
  "there is a question named 'q29' that has 'eats' as relationship and concerns the sherlock thing 'eliffant'",
  "there is a question named 'q30' that has 'is played by' as relationship and concerns the sherlock thing 'golff'",
  "there is a question named 'q31' that has 'is eaten by' as relationship and concerns the sherlock thing 'oren'",
  "there is a question named 'q32' that has 'coloured hat' as relationship and concerns the sherlock thing 'sebra'",
  "there is a question named 'q33' that has 'is eaten by' as relationship and concerns the sherlock thing 'afal'",
  "there is a question named 'q34' that has 'contents' as value and concerns the sherlock thing 'ystafell aberystwyth'",
  "there is a question named 'q35' that has 'is worn by' as relationship and concerns the sherlock thing 'gwyrdd'",
  "there is a question named 'q36' that has 'is in' as relationship and concerns the sherlock thing 'hipopotamws'"
];
